management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8099

spring:
  security:
    user:
      name: client
      password: ${SBA_PASS:714df93cf5c9}
  application:
    name: "Admin"
  boot:
    admin:
      client:
        url: http://localhost:8099
        username: client
        password: ${SBA_PASS:714df93cf5c9}
        instance:
          metadata:
            user:
              name: client
              password: ${SBA_PASS:714df93cf5c9}

logging:
  pattern:
    dateformat: MM-dd HH:mm:ss.SSS,America/Los_Angeles

